# lecture notes:

#### 1. Here’s a question we got from the week 1 survey:

> “One thing that’s confusing is why sometimes I need to &var and other times I can just use var: for example, set.contains(&var), but set.insert(var) – why?"

Can you answer this question based on your understanding of references now?

> When inserting an item into a set, we want to transfer ownership of that item into the set; that way, the item will exist as long as the set exists. (It would be bad if you added a string to the set, and then someone freed the string while it was still a member of the set.) However, when trying to see if the set contains an item, we want to retain ownership, so we only pass a reference.

----

#### 2. Handling nulls
Rust does this with the Option type. A value of type `Option<T>` can either be `None` or `Some(value of type T)`

```rust
fn feeling_lucky() -> Option<String> {
    if get_random_num() > 10 {
        Some(String::from("I'm feeling lucky!"))
    } else {
        None
    }
}
```

----

#### 3. Handling errors

Rust takes a different, two-pronged approach to error handling:

* If an unrecoverable error occurs – one where you think, crap, this program is a dumpster fire… – you should `panic`. Panics terminate the program immediately and cannot be caught. (Side note: it’s technically possible to catch and recover from panics, but doing so really defeats the philosophy of error handling in Rust, so it’s not advised.)  
    > 
    ```rust
    if sad_times() {
    panic!("Sad times!");
    }
    ```

* If it’s possible for a recoverable error to occur, you should return a `Result`. If you return `Result<T, E>`, you can either return `Ok(value of type T)` or `Err(value of type E)`.
    >
    ```rust
    fn poke_toddler() -> Result<&'static str, &'static str> {
        if get_random_num() > 10 {
            Ok("Hahahaha!")
        } else {
            Err("Waaaaahhh!")
        }
    }

    fn main() {
        match poke_toddler() {
            Ok(message) => println!("Toddler said: {}", message),
            Err(cry) => println!("Toddler cried: {}", cry),
        }
    }
    ```

